import { useGLTF } from '@react-three/drei'

/**
 * BuildingSet Component
 * 
 * This functional React component sets up a 3D object using `@react-three/fiber` 
 * to visualize an 3d object imported in this proyect.
 * This is a set of many different buildings which will be used for the
 * environment of the scene.
 */

export function BuildingSet(props) {
  const { nodes, materials } = useGLTF('/models-3d/buildingsSet.glb');

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-3589.953, 941.93, 1567.613]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_brick_modern_03_0.geometry}
            material={materials.brick_modern_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_Shops_01_0.geometry}
            material={materials.Shops_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_Shops_02_0.geometry}
            material={materials.Shops_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_Shops_0.geometry}
            material={materials.Shops}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_building_09_0.geometry}
            material={materials.building_09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_03_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group position={[245.602, 1190.5, -3091.816]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_brick_modern_03_0.geometry}
            material={materials.brick_modern_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_building_04_0.geometry}
            material={materials.building_04}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_Shops_03_0.geometry}
            material={materials.Shops_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_Shops_04_0.geometry}
            material={materials.Shops_04}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_Shops_05_0.geometry}
            material={materials.Shops_05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_01_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group
          position={[-3341.285, 996.643, -3150.081]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_brick_modern_04_0.geometry}
            material={materials.brick_modern_04}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_building_06_0.geometry}
            material={materials.building_06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_Shops_06_0.geometry}
            material={materials.Shops_06}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_Shops_09_0.geometry}
            material={materials.Shops_09}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_Shops_08_0.geometry}
            material={materials.Shops_08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group
          position={[4273.21, 1363.928, -3196.562]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_brick_modern_02_0.geometry}
            material={materials.brick_modern_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_Shops_11_0.geometry}
            material={materials.Shops_11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_building_08_0.geometry}
            material={materials.building_08}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_Shops_10_0.geometry}
            material={materials.Shops_10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_Shops_12_0.geometry}
            material={materials.Shops_12}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_Shops_14_0.geometry}
            material={materials.Shops_14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_02_Shops_13_0.geometry}
            material={materials.Shops_13}
          />
        </group>
        <group position={[-335.618, 941.408, 1410.297]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_brick_modern_03_0.geometry}
            material={materials.brick_modern_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_Shops_16_0.geometry}
            material={materials.Shops_16}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_building_01_0.geometry}
            material={materials.building_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_Shops_15_0.geometry}
            material={materials.Shops_15}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_Shops_17_0.geometry}
            material={materials.Shops_17}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_04_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group position={[4652.102, 602.338, 5507.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_09_building_10_0.geometry}
            material={materials.building_10}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_09_brick_modern_0.geometry}
            material={materials.brick_modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_09_Shops_18_0.geometry}
            material={materials.Shops_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_09_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_09_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_09_Shops_07_0.geometry}
            material={materials.Shops_07}
          />
        </group>
        <group position={[3431.76, 951.746, 1366.619]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_brick_modern_01_0.geometry}
            material={materials.brick_modern_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_building_03_0.geometry}
            material={materials.building_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_Shops_19_0.geometry}
            material={materials.Shops_19}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_Shops_21_0.geometry}
            material={materials.Shops_21}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_Shops_20_0.geometry}
            material={materials.Shops_20}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_Shops_22_0.geometry}
            material={materials.Shops_22}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_05_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group position={[77.515, 866.631, 5424.901]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_brick_modern_05_0.geometry}
            material={materials.brick_modern_05}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_building_0.geometry}
            material={materials.building}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_Shops_23_0.geometry}
            material={materials.Shops_23}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_Shops_24_0.geometry}
            material={materials.Shops_24}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_Shops_25_0.geometry}
            material={materials.Shops_25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_07_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group position={[2593.215, 597.941, 5485.315]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_08_BrickSmallPainted_0.geometry}
            material={materials.BrickSmallPainted}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_08_Shops_26_0.geometry}
            material={materials.Shops_26}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_08_Shops_27_0.geometry}
            material={materials.Shops_27}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_08_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_08_building_11_0.geometry}
            material={materials.building_11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_08_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
        <group
          position={[-3126.157, 738.981, 5352.491]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_BrickSmallBrown_0.geometry}
            material={materials.BrickSmallBrown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_Shops_28_0.geometry}
            material={materials.Shops_28}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_building_07_0.geometry}
            material={materials.building_07}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_Shops_29_0.geometry}
            material={materials.Shops_29}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_ConcreteBare_0.geometry}
            material={materials.ConcreteBare}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_Shops_31_0.geometry}
            material={materials.Shops_31}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_Shops_30_0.geometry}
            material={materials.Shops_30}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Building_06_Roof_tiles_0.geometry}
            material={materials.Roof_tiles}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models-3d/buildingsSet.glb')
