name: Run Tests

on:
  push:
    branches:
      - main # Ejecuta las pruebas cuando se haga push en la rama 'main'.
  pull_request:
    branches:
      - main # Ejecuta las pruebas cuando se abra un pull request hacia 'main'.

jobs:
  test:
    runs-on: ubuntu-latest # El sistema operativo donde se ejecutar치n las pruebas.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Descarga el c칩digo del repositorio.

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Asegura que se usar치 Node.js versi칩n 18.

      - name: Install dependencies
        run: npm install # Instala las dependencias del proyecto.

      - name: Run tests
        run: npm test # Ejecuta los tests definidos en tu proyecto.
